server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.101
  rabbitmq:
    host: 192.168.56.101
    virtual-host: /fengge
    username: fengge
    password: fengge
gmall:
  jwt:
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
