server:
  port: 8092
spring:
  rabbitmq:
    host: 192.168.56.101
    virtual-host: /gbf
    username: gbf
    password: gbf
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.101

gmall:
  jwt:
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
alipay:
  app_id: 2016101400687511
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSdGBMGZnTCCo1pAeoaVZIKambZU1+Wtvo6MlVeAgcog9WJ2zYwToASOFnLDtxybu5D5J8hrfW/esJBf0p8XvjtpdP8xza/qZW+4+8aDrV0bOsU5/bBZT4nStNP4E05dZasBQC/bHQ4rAoyshGUpghFryxfh7RI6rnuR5gxcs9AN44VNNhZmFHu6iftqcDMA2tyJbR0R0H+SUn1W7Ct7CiqwTLcdSKGGFoiItQP2G9VqoQTni2vE5C8XdtSdeuvRFA7HGja8e7MHB7MoTn59Z6KDJ7tcaPdd9rm55VYcOOvve8wU1i0GYaDTVp4e5JzBIHw9nD7LqRAzZOvnEskMVhAgMBAAECggEATTHqUDJuUj3Lgdqj7rEXOZI8RBxxbFiX8XxCIzrRi8YgL1k4lkfDOsMvjCJUcvXSbQk4PUsFO907NdZiSuluU+i6ePm8C/KN2uteKAEIggu2mO67I8cdbq3pVR5UDH3ZLpQA+FKgl2nlUJsSVX7TkR1a+HNx6urR+rIowPmA1vYCCQuhacJtnS6zeENoS7nl6VfY1PRTrs35fjFqVdlVpHB4C1uNVCcQFkEL+YDC9nA5VXSvaZdKcKUZZmxkS5dDyQVPwuZgkFg6vnPSfe88Xukk5VWv3Br0hxC9OiRLLG6/liiFYLMcHOgz4cocd++vSywON7WUlN87wfDLktjywQKBgQDDt9L46U9mKM06LLwcN5nGoC3fWi52zwtst7woXDxvwB3nXgCFcO2UEgglw5exfzhYkJpXu1T2pL8Otns4nf/u8WsmizfluL/WYqZKk9eStOfYXkQk2NVY1X1+kk6TpUPyeI3nPWTyoRM6isJA5igEPXjsequN5MU5alt0u1DGiwKBgQC/kC0dTfe90j3e7Hcon3YhzAzEpxX1DOzykTfsHLOb90GcGEe+cOEEnOz+T/g52l/kIc7j7fSIh6vfUhhpxEq3HjrLr5NPDBkDOJK+DOgcTJ8QX6XiUpbqpbr3ArzTibfg0/hh7YI9o946WlYdi2Q1Mdd8Qf5TmyOo7vcaS79NQwKBgQCMfnfG0Ix7lEyGNzittMgBiliDndP+22+jEl3SRyvnOGz++j67i64v/aW1nitVcjK7eMoiskoyZ17zK9FWei0PlGPLnmJ42F91gQlIPcqg+JX5funB3ZmBFHfqlRIs8JTPCPUsiqjddv07qAH73nvZV1tnvkNKL2/YYF3YdOJuMwKBgE7G9LaTZKksN4NgTRRol0UIy8tnRvFSUnLiY1P27anbAaE2nvJjKzYhbpiavGLWOg7wFEvJhIFNAdJByYZdUbiCdv1ig7rDJ9oaPsZnOmDA5bzvCKHNAwEWDJAeERcREIwlv4RODvxYUkA+/CEEPL5fc9VGslcheoWzV+z5b39PAoGABXdh5+0oOPYXWUVsDMnEZIw0G02T3AeoibHYqWyxEauXAb+KxMNz5T+9xFI9ldv4dXs6svm+DPcSwfVvkF4HJql/MU97L+2rVssoFZCWv9NjBRIjg558j34o0l89tQfGdGPatc11LO70xXWKy559b49Me94g53ADCHXjvocqXdw=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgAtRj4WA7uAsZXuhOhJtroZ9II/Da4GHEnjcW4+GSxNeIxTtkI8m3hHOyGqZVcITbAY97nleumzqTA+MsFBtYM5PagUcnFx4Cdt6HcWNib+w+3t5iNkNNdkkGE+xQgKZfm/wGPHaXgUm192/EMMosd4ZQK6nsKcdwXYBAzGN5+5Yqvf0eSXElytMXtvG0VEZVsc/GZOUIrWXy7ADHlW206dvzLUxGH+MCrcvEUv9U1/9n/iW3nxZtpRY1ip+cRRyaNs7kkrUnnvBRDpGkvTtYwofArwdiZEQdYewSS5my8s/0O7PVjbKssQPED5akO+t5Y7OiKKSKs726aOBllmoCwIDAQAB
  notify_url: http://35mrubvkij.52http.net/api/order/pay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://www.baidu.com
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

  #生成的from表单复制到日记本要修改成Uff-8的格式，不然系统无法解析
