server:
  port: 8090
spring:
  rabbitmq:
    host: 192.168.56.101
    username: gbf
    password: gbf
    virtual-host: /gbf
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.101

gmall:
  jwt:
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key