server:
  port: 8081
spring:
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    virtual-host: /gbf
    username: gbf
    password: gbf
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.101/guli_pms
    username: root
    password: root
  redis:
    host: 192.168.56.101
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/pms/**/*.xml


item:
  rabbitmq:
    exchange: GMALL-PMS-EXCHANGE
